import { useEffect, useState, type ReactNode } from "react";
import { Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { Activity, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, BarChart3, Bell, BriefcaseBusiness, CalendarDays, Check, CheckCircle2, ChevronRight, CircleAlert, Clock3, Copy, ExternalLink, FileBarChart, FileText, Gauge, Globe2, LayoutDashboard, Link2, LockKeyhole, LogOut, Menu, MoreHorizontal, Play, Plus, RefreshCcw, Search, Settings, Share2, ShieldCheck, Sparkles, Users, XCircle } from "lucide-react";
import { StoreProvider, useStore } from "./store";
import { can, roles, type JobState, type ReportPage, type Role } from "./domain";
import { Button } from "./components/ui/button";
import { Badge } from "./components/ui/badge";
import { Card, CardContent, CardHeader } from "./components/ui/card";
import { Dialog, DialogContent, DialogTitle, DialogTrigger } from "./components/ui/dialog";
import { Input, Textarea } from "./components/ui/input";
import { Progress } from "./components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./components/ui/tabs";
import BaselinePage from "./pages/BaselinePage";

const titleCase = (text: string) => text.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
const statusTone = (status: string) => status === "completed" || status === "approved" || status === "published" || status === "locked" ? "success" : status === "failed" || status === "changes_requested" ? "danger" : status === "running" || status === "in_review" ? "info" : "warning";
const Status = ({ value }: { value: string }) => <Badge className={`status ${statusTone(value)}`}><span className="status-dot" />{titleCase(value)}</Badge>;
const exactTime = (date = new Date()) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(date);
function LiveTime() {
  const [now, setNow] = useState(new Date());
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 60000); return () => window.clearInterval(timer); }, []);
  return <div className="live-time"><CalendarDays size={15} /><span><strong>{new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric" }).format(now)}</strong><small>{new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit", timeZoneName: "short" }).format(now)}</small></span></div>;
}

const mainNav = [
  { to: "/app", label: "Overview", icon: LayoutDashboard },
  { to: "/app/workspaces", label: "Workspaces", icon: BriefcaseBusiness },
  { to: "/app/admin", label: "Organization admin", icon: Users },
  { to: "/app/run", label: "Active run", icon: Activity },
  { to: "/app/jobs", label: "Jobs", icon: Gauge },
  { to: "/app/notifications", label: "Notifications", icon: Bell },
];

function AppShell({ children }: { children: ReactNode }) {
  const { state, setRole, selectWorkspace, signOut } = useStore();
  const [mobileOpen, setMobileOpen] = useState(false);
  const location = useLocation();
  const pageTitle = location.pathname.split("/").filter(Boolean).at(-1)?.replaceAll("-", " ") ?? "Overview";
  const unread = state.notifications.filter((n) => !n.read).length;
  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? "open" : ""}`}>
      <Link to="/app" className="brand"><span className="brand-mark"><BarChart3 /></span><span><b>SignalOps</b><small>Report workspace</small></span></Link>
      <div className="scope-card"><small>ORGANIZATION</small><strong>CXOntology</strong><label><i /><select value={state.selectedWorkspaceId} onChange={(event) => selectWorkspace(event.target.value)}>{state.workspaces.map((workspace) => <option value={workspace.id} key={workspace.id}>{workspace.name}</option>)}</select></label></div>
      <nav>{mainNav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === "/app"} onClick={() => setMobileOpen(false)}><Icon size={18} />{label}{label === "Notifications" && unread > 0 && <b className="nav-count">{unread}</b>}</NavLink>)}</nav>
      <div className="sidebar-bottom">
        <NavLink to="/app/settings"><Settings size={18} />Settings</NavLink>
        <div className="user-card"><div className="avatar">AS</div><span><strong>Alex Smith</strong><small>{titleCase(state.role)}</small></span><MoreHorizontal size={18} /></div>
      </div>
    </aside>
    <main className="main">
      <header className="topbar">
        <Button variant="ghost" size="icon" className="mobile-menu" onClick={() => setMobileOpen(!mobileOpen)}><Menu /></Button>
        <div><small>CXONTOLOGY / {state.workspaceName.toUpperCase()}</small><h2>{titleCase(pageTitle)}</h2></div>
        <div className="top-actions">
          <LiveTime />
          <label className="role-switch"><ShieldCheck size={16} /><span>Demo role</span><select value={state.role} onChange={(e) => setRole(e.target.value as Role)}>{roles.map((r) => <option key={r} value={r}>{titleCase(r)}</option>)}</select></label>
          <Link to="/app/notifications" className="icon-link"><Bell size={18} />{unread > 0 && <i />}</Link>
          <Button variant="ghost" size="icon" onClick={signOut} title="Sign out"><LogOut size={18} /></Button>
        </div>
      </header>
      <div className="content">{children}</div>
    </main>
  </div>;
}

function Login() {
  const { state, signIn } = useStore(); const navigate = useNavigate();
  if (state.signedIn) return <Navigate to="/app" />;
  return <div className="login-page"><div className="login-visual"><div className="brand hero-brand"><span className="brand-mark"><BarChart3 /></span><b>SignalOps</b></div><div><Badge className="eyebrow">REPORT INTELLIGENCE</Badge><h1>Turn digital signals into decisions.</h1><p>Configure, generate, review, and publish multi-page assessments from one operational workspace.</p></div><div className="signal-grid"><span>126<small>Evidence points</small></span><span>+14%<small>Opportunity</small></span><span>4<small>Reports ready</small></span></div></div><Card className="login-card"><CardHeader><h2>Welcome back</h2><p>Sign in to your report workspace</p></CardHeader><CardContent><label>Email<Input defaultValue="analyst@example.com" /></label><label>Password<Input type="password" defaultValue="password" /></label><Button onClick={() => { signIn(); navigate("/app"); }}>Sign in <ArrowRight size={17} /></Button><Button variant="secondary">Continue with SSO</Button><small>This is a frontend demo. Any credentials work.</small></CardContent></Card></div>;
}

const PageHead = ({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: ReactNode }) => <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{actions && <div className="head-actions">{actions}</div>}</div>;
const Stat = ({ icon: Icon, label, value, change, color = "violet" }: { icon: typeof Activity; label: string; value: string; change: string; color?: string }) => <Card className="stat-card"><div className={`stat-icon ${color}`}><Icon size={20} /></div><span>{label}</span><strong>{value}</strong><small>{change}</small></Card>;

function Dashboard() {
  const { state, retryJob } = useStore();
  return <><PageHead eyebrow={`ORGANIZATION OVERVIEW · ${exactTime()}`} title="Good afternoon, Alex." description="Monitor every customer workspace, active engagement, generation job, and publication from one admin dashboard." actions={<><span className="sync-label"><RefreshCcw size={14} />Last synced {exactTime()}</span><Link to="/app/workspaces"><Button variant="secondary"><BriefcaseBusiness size={17} />All customers</Button></Link><Link to="/app/workspaces/new"><Button><Plus size={17} />New customer</Button></Link></>} />
    <div className="stats-grid"><Stat icon={BriefcaseBusiness} label="Customer workspaces" value={String(state.workspaces.length)} change="All active" /><Stat icon={Activity} label="Active report runs" value="4" change="Across 4 customers" /><Stat icon={CircleAlert} label="Needs attention" value="2" change="1 baseline, 1 failed job" color="orange" /><Stat icon={CheckCircle2} label="Reports published" value="18" change="+3 this month" color="green" /></div>
    <Card className="portfolio-card"><CardHeader><div><span className="eyebrow">CUSTOMER PORTFOLIO</span><h3>Workspace health and active engagements</h3></div><Link to="/app/workspaces">Manage all customers</Link></CardHeader><CardContent><table><thead><tr><th>Customer</th><th>Active engagement</th><th>Owner</th><th>Reports</th><th>Health</th><th /></tr></thead><tbody>{state.workspaces.map((workspace) => <tr key={workspace.id}><td><Link to={`/app/workspaces/${workspace.id}`} className="client-cell"><span className="client-logo">{workspace.name.slice(0,2)}</span><span><strong>{workspace.name}</strong><small className="table-sub">{workspace.domain}</small></span></Link></td><td>{workspace.activeEngagement}</td><td>{workspace.owner}</td><td>{workspace.reportCount}</td><td><b className="score-cell">{workspace.healthScore || "—"}</b></td><td><ChevronRight size={16} /></td></tr>)}</tbody></table></CardContent></Card>
    <div className="dashboard-grid"><Card className="span-2"><CardHeader><div><span className="eyebrow">ACTIVE RUN · UPDATED {exactTime()}</span><h3>{state.runLabel}</h3><p>Lysol · Digital health assessment · Started June 11, 2026 at 9:00 AM</p></div><Status value="running" /></CardHeader><CardContent><Pipeline compact /><div className="attention-row"><div className="alert-icon"><CircleAlert /></div><div><strong>Baseline validation needs input</strong><p>Two source conflicts need to be resolved before locking · Waiting since 10:42 AM</p></div><Button variant="secondary" onClick={() => location.assign("/app/run/baseline")}>Review baseline</Button></div></CardContent></Card>
    <Card><CardHeader><h3>Recent activity</h3><Link to="/app/notifications">View all</Link></CardHeader><CardContent className="activity-list">{state.notifications.map((n) => <div key={n.id}><span className={`activity-dot ${n.read ? "" : "active"}`} /><div><strong>{n.title}</strong><p>{n.message}</p><small>Today</small></div></div>)}</CardContent></Card>
    <Card className="span-2"><CardHeader><h3>Jobs requiring attention</h3><Link to="/app/jobs">View all jobs</Link></CardHeader><CardContent><JobTable jobs={state.jobs.filter((j) => j.state !== "completed")} onRetry={retryJob} /></CardContent></Card>
    <Card><CardHeader><h3>Assessment health</h3><Status value={state.assessmentStatus} /></CardHeader><CardContent><ScoreRing score={78} /><div className="mini-bars"><span><i style={{ width: "88%" }} />Experience <b>88</b></span><span><i style={{ width: "74%" }} />Discovery <b>74</b></span><span><i style={{ width: "69%" }} />Conversion <b>69</b></span></div></CardContent></Card></div></>;
}

function Workspaces() {
  const { state, selectWorkspace } = useStore();
  return <><PageHead eyebrow="CUSTOMER PORTFOLIO" title="All customer workspaces" description="Create and manage every customer's engagements, teams, assessments, and published report sets." actions={<Link to="/app/workspaces/new"><Button><Plus size={17} />New customer</Button></Link>} /><div className="stats-grid three"><Stat icon={BriefcaseBusiness} label="Active customers" value={String(state.workspaces.filter((workspace) => workspace.status === "active").length)} change="Across the organization" /><Stat icon={FileBarChart} label="Total report sets" value={String(state.workspaces.reduce((sum, workspace) => sum + workspace.reportCount, 0))} change="All customer workspaces" color="blue" /><Stat icon={Users} label="Portfolio owners" value="3" change="Organization-wide access" color="green" /></div><Card><CardHeader><div className="search"><Search size={17} /><Input placeholder="Search customers..." /></div><div className="filter-row"><Badge>All customers</Badge><Badge>Active</Badge><Badge>Updated recently</Badge></div></CardHeader><CardContent><table><thead><tr><th>Customer</th><th>Industry</th><th>Active engagement</th><th>Health</th><th>Owner</th><th>Updated</th><th /></tr></thead><tbody>{state.workspaces.map((workspace,i)=><tr key={workspace.id}><td><Link to={`/app/workspaces/${workspace.id}`} onClick={() => selectWorkspace(workspace.id)} className="client-cell"><span className={`client-logo c${i%4}`}>{workspace.name.slice(0,2)}</span><span><strong>{workspace.name}</strong><small className="table-sub">{workspace.domain}</small></span></Link></td><td>{workspace.industry}</td><td>{workspace.activeEngagement}</td><td><b className="score-cell">{workspace.healthScore || "—"}</b></td><td>{workspace.owner}</td><td>{workspace.updatedAt}</td><td><ChevronRight size={17} /></td></tr>)}</tbody></table></CardContent></Card></>;
}

function WorkspaceOverview() {
  const { id } = useParams(); const { state } = useStore();
  const workspace = state.workspaces.find((item) => item.id === id) ?? state.workspaces[0];
  const hasReports = workspace.reportCount > 0;
  return <><PageHead eyebrow="CUSTOMER WORKSPACE" title={workspace.name} description={`${workspace.industry} · ${workspace.domain} · Owned by ${workspace.owner}`} actions={<Link to={`/app/workspaces/${workspace.id}/new-run`}><Button><Plus size={17} />Start new report run</Button></Link>} /><div className="hero-score"><div><span className="eyebrow">{hasReports ? "LATEST ASSESSMENT" : "NEW CUSTOMER WORKSPACE"}</span><h2>{workspace.activeEngagement}</h2><p>{hasReports ? "Structured digital assessment with competitive intelligence and prioritized recommendations." : "This customer is ready for its first engagement and report run."}</p><div><Status value={hasReports ? state.assessmentStatus : "draft"} /><span>Updated {workspace.updatedAt.toLowerCase()}</span></div></div><ScoreRing score={workspace.healthScore} /></div><div className="stats-grid three"><Stat icon={Globe2} label="Primary domain" value={workspace.domain} change="Customer digital property" color="blue" /><Stat icon={FileBarChart} label="Report sets" value={String(workspace.reportCount)} change={hasReports ? "Available in this workspace" : "Start the first report run"} /><Stat icon={Users} label="Workspace team" value={String(workspace.memberCount)} change={`Owner: ${workspace.owner}`} color="green" /></div><Card><CardHeader><h3>Engagements and assessment history</h3><Button variant="secondary">Manage customer access</Button></CardHeader><CardContent>{hasReports?<JobTable jobs={[{id:"r1",type:"Assessment",label:workspace.activeEngagement,state:"running",progress:86,updatedAt:workspace.updatedAt},{id:"r2",type:"Assessment",label:"Previous digital assessment",state:"completed",progress:100,updatedAt:"Mar 28"}]} />:<div className="empty-small"><BriefcaseBusiness/><strong>No engagements yet</strong><p>Start a report run to configure this customer's first assessment.</p></div>}</CardContent></Card></>;
}

function CreateWorkspace() {
  const { addWorkspace } = useStore(); const navigate = useNavigate();
  const [form, setForm] = useState({ name: "", industry: "", domain: "", owner: "Alex Smith" });
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <><PageHead eyebrow="ORGANIZATION ADMIN" title="Create customer workspace" description="Add a customer to the portfolio, assign ownership, and prepare its first engagement." /><Card className="create-workspace"><CardHeader><div><h2>Customer details</h2><p>These details define the top-level workspace visible to your organization team.</p></div></CardHeader><CardContent><div className="form-grid"><label>Customer name<Input value={form.name} onChange={(event) => set("name", event.target.value)} placeholder="Example: Contoso Health" /></label><label>Industry<Input value={form.industry} onChange={(event) => set("industry", event.target.value)} placeholder="Example: Healthcare" /></label><label>Primary domain<Input value={form.domain} onChange={(event) => set("domain", event.target.value)} placeholder="contoso.com" /></label><label>Workspace owner<select className="input" value={form.owner} onChange={(event) => set("owner", event.target.value)}><option>Alex Smith</option><option>Priya Rao</option><option>Marco Lee</option></select></label></div><div className="wizard-actions"><Link to="/app/workspaces"><Button variant="secondary">Cancel</Button></Link><span>The customer will be stored in this browser.</span><Button disabled={!form.name || !form.industry || !form.domain} onClick={() => navigate(`/app/workspaces/${addWorkspace(form)}`)}>Create customer workspace<ArrowRight size={16} /></Button></div></CardContent></Card></>;
}

function OrganizationAdmin() {
  const { state } = useStore();
  return <><PageHead eyebrow="ORGANIZATION ADMIN" title="Portfolio administration" description="Manage customer workspaces, organization users, roles, templates, and operational health." actions={<Link to="/app/workspaces/new"><Button><Plus size={16} />Add customer</Button></Link>} /><div className="stats-grid"><Stat icon={BriefcaseBusiness} label="Customers" value={String(state.workspaces.length)} change="All customer workspaces" /><Stat icon={Users} label="Organization users" value="24" change="5 roles configured" color="green" /><Stat icon={FileBarChart} label="Report templates" value="8" change="4 active template families" color="blue" /><Stat icon={Activity} label="Platform success" value="98.4%" change="Generation success rate" color="orange" /></div><div className="dashboard-grid"><Card className="span-2"><CardHeader><h3>Customer portfolio health</h3><Link to="/app/workspaces">Manage customers</Link></CardHeader><CardContent><table><thead><tr><th>Customer</th><th>Owner</th><th>Members</th><th>Reports</th><th>Health</th><th>Status</th></tr></thead><tbody>{state.workspaces.map((workspace) => <tr key={workspace.id}><td><Link to={`/app/workspaces/${workspace.id}`}><strong>{workspace.name}</strong><small className="table-sub">{workspace.domain}</small></Link></td><td>{workspace.owner}</td><td>{workspace.memberCount}</td><td>{workspace.reportCount}</td><td><b className="score-cell">{workspace.healthScore || "—"}</b></td><td><Status value={workspace.status} /></td></tr>)}</tbody></table></CardContent></Card><Card><CardHeader><h3>Admin controls</h3></CardHeader><CardContent className="admin-links">{["Organization team & roles","Report template registry","Integration readiness","Audit activity","Notification policies"].map((item) => <button key={item}><span><Settings size={16} />{item}</span><ChevronRight size={16} /></button>)}</CardContent></Card></div></>;
}

function NewRun() {
  const navigate = useNavigate(); const { state } = useStore(); const [step, setStep] = useState(1);
  const steps = ["Scope", "Properties", "Competitors", "Tools", "Data access", "Templates", "Review"];
  return <><PageHead eyebrow="NEW REPORT RUN" title={`Configure ${state.workspaceName} assessment`} description={`Build a resumable report run inside the ${state.workspaceName} customer workspace.`} /><div className="wizard"><aside>{steps.map((s,i)=><button key={s} className={step===i+1?"active":step>i+1?"done":""} onClick={()=>setStep(i+1)}><span>{step>i+1?<Check size={15}/>:i+1}</span>{s}</button>)}</aside><Card><CardHeader><span className="eyebrow">STEP {step} OF 7</span><h2>{steps[step-1]}</h2><p>{step===1?"Define the business context and assessment scope.":"Review and configure the inputs for this generation stage."}</p></CardHeader><CardContent><RunStep step={step} workspaceName={state.workspaceName}/><div className="wizard-actions"><Button variant="secondary" disabled={step===1} onClick={()=>setStep(step-1)}><ArrowLeft size={16}/>Back</Button><span>Draft saved just now</span><Button onClick={()=>step===7?navigate("/app/run"):setStep(step+1)}>{step===7?"Start report run":"Continue"}<ArrowRight size={16}/></Button></div></CardContent></Card></div></>;
}
function RunStep({step,workspaceName}:{step:number;workspaceName:string}) {
  if(step===1)return <div className="form-grid"><label>Report label<Input defaultValue={`${workspaceName} Digital Assessment`}/></label><label>Geography<Input defaultValue="United States"/></label><label className="full">Assessment objective<Textarea defaultValue={`Benchmark ${workspaceName}'s digital health and identify high-confidence opportunities across experience, visibility, and competitive position.`}/></label></div>;
  if(step===6)return <div className="choice-grid">{["Digital Health Assessment","Competitive Position Report","Competitive Signal Dashboard","Executive Summary"].map((x,i)=><label className="choice-card" key={x}><input type="checkbox" defaultChecked/><span><FileBarChart/><strong>{x}</strong><small>{i===3?"Leadership-ready narrative":"Core report template"}</small></span></label>)}</div>;
  if(step===7)return <div className="review-grid">{[`${workspaceName} · United States`,"Primary domain + connected properties","3 tracked competitors","8 digital tools","All access verified","4 report templates"].map((x,i)=><div key={x}><CheckCircle2/><span><small>{["Scope","Properties","Competitors","Tools","Data access","Reports"][i]}</small><strong>{x}</strong></span></div>)}</div>;
  return <div className="choice-grid">{["Lysol.com","Clorox portfolio","PageSpeed & Core Web Vitals","Accessibility scanner","SEO visibility","Competitive health snapshot"].map((x,i)=><label className="choice-card" key={x}><input type="checkbox" defaultChecked={i<4}/><span><Sparkles/><strong>{x}</strong><small>Ready for assessment</small></span></label>)}</div>;
}

const stages = ["Configuration","Tools","Baseline","Snapshots","Assessment","Preview","Review","Published"];
function Pipeline({compact=false}:{compact?:boolean}) { return <div className={`pipeline ${compact?"compact":""}`}>{stages.map((s,i)=><Link key={s} to={i===2?"/app/run/baseline":i===3?"/app/run/snapshots":i===4?"/app/run/assessment":i===5?"/app/run/preview":i===6?"/app/run/review":"/app/run"} className={i<2?"done":i===2?"active":""}><span>{i<2?<Check size={15}/>:i+1}</span><small>{s}</small></Link>)}</div> }
function RunCommand() {
  const {state,retryJob}=useStore();
  return <><PageHead eyebrow="ACTIVE REPORT RUN" title={state.runLabel} description="Lysol · Run #06-2026 · Started today by Alex Smith" actions={<><Button variant="secondary">Cancel run</Button><Link to="/app/run/baseline"><Button>Continue review<ArrowRight size={16}/></Button></Link></>} /><Card className="pipeline-card"><Pipeline/></Card><div className="run-grid"><Card className="span-2"><CardHeader><div><span className="eyebrow">CURRENT STAGE</span><h2>Baseline validation</h2><p>Resolve source conflicts and lock the normalized baseline.</p></div><Status value="waiting_for_input"/></CardHeader><CardContent><Progress value={86}/><div className="attention-row"><div className="alert-icon"><CircleAlert/></div><div><strong>Two source conflicts require your decision</strong><p>Analytics and crawler values differ for page count and mobile performance.</p></div><Link to="/app/run/baseline"><Button>Resolve issues</Button></Link></div></CardContent></Card><Card><CardHeader><h3>Run health</h3></CardHeader><CardContent><ScoreRing score={86}/><div className="summary-list"><span><b>8 / 8</b> tools completed</span><span><b>126</b> evidence points</span><span><b>2</b> open issues</span></div></CardContent></Card><Card className="span-2"><CardHeader><h3>Generation activity</h3><Link to="/app/jobs">Open all jobs</Link></CardHeader><CardContent><JobTable jobs={state.jobs} onRetry={retryJob}/></CardContent></Card><Card><CardHeader><h3>Configuration</h3></CardHeader><CardContent className="summary-list"><span><small>Primary domain</small><b>lysol.com</b></span><span><small>Geography</small><b>United States</b></span><span><small>Competitors</small><b>3 selected</b></span><span><small>Report pages</small><b>{state.pages.length} templates</b></span></CardContent></Card></div></>;
}

function JobTable({jobs,onRetry}:{jobs:{id:string;type:string;label:string;state:JobState;progress?:number;updatedAt:string}[];onRetry?:(id:string)=>void}) {
  return <table><thead><tr><th>Job</th><th>State</th><th>Progress</th><th>Updated</th><th/></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><strong>{j.label}</strong><small className="table-sub">{titleCase(j.type)}</small></td><td><Status value={j.state}/></td><td><div className="table-progress"><Progress value={j.progress??0}/><span>{j.progress??"—"}{j.progress!==undefined?"%":""}</span></div></td><td>{j.updatedAt}</td><td>{j.state==="failed"&&onRetry?<Button variant="secondary" size="sm" onClick={()=>onRetry(j.id)}><RefreshCcw size={14}/>Retry</Button>:<MoreHorizontal size={17}/>}</td></tr>)}</tbody></table>;
}

function Tools() {
  const tools=[["PageSpeed Insights","completed","14","Performance improved 7 points","Jun 11, 2026 · 10:24 AM"],["Accessibility scanner","completed","23","11 issues resolved since last run","Jun 11, 2026 · 10:28 AM"],["SEO visibility","completed","31","Visibility index increased 8 points","Jun 11, 2026 · 10:31 AM"],["Security headers","completed","8","All critical controls present","Jun 11, 2026 · 10:34 AM"],["Retail journey crawler","failed","0","Retail API returned an invalid response","Jun 11, 2026 · 10:39 AM"]];
  return <><StageNav/><PageHead eyebrow={`TOOLS REPORT · UPDATED ${exactTime()}`} title="Collection and evidence" description="Monitor each selected tool and inspect the evidence collected for the baseline." actions={<Button><Play size={16}/>Run unavailable tools</Button>}/><Card><CardContent><table><thead><tr><th>Tool</th><th>State</th><th>Artifacts</th><th>Latest result</th><th>Last run</th><th/></tr></thead><tbody>{tools.map(t=><tr key={t[0]}><td><strong>{t[0]}</strong></td><td><Status value={t[1]}/></td><td>{t[2]}</td><td>{t[3]}</td><td><small>{t[4]}</small></td><td><Button variant="ghost" size="icon"><ChevronRight size={17}/></Button></td></tr>)}</tbody></table></CardContent></Card></>;
}
function StageNav(){return <div className="stage-nav"><Link to="/app/run"><ArrowLeft size={16}/>Command center</Link><Link to="/app/run/tools">Tools</Link><Link to="/app/run/baseline">Baseline</Link><Link to="/app/run/snapshots">Snapshots</Link><Link to="/app/run/assessment">Assessment</Link><Link to="/app/run/preview">Preview</Link><Link to="/app/run/review">Review</Link></div>}

const baselineModules=[
  ["CWV","Technical foundation"],["Accessibility","Technical foundation"],["Best Practices","Technical foundation"],["SEO","Findability"],["GEO","Findability"],["Content","Findability"],["Security","Technical foundation"],["Infrastructure","Technical foundation"],["Data Layer & Cookies","Data & measurement"],["Technology Profile","Technical foundation"],
  ["Peak Usage Reliability","Operations"],["Release Stability","Operations"],["Sustainability","Operations"],["Service Worker PWA","Experience"],["User Journey Analysis","Experience"],["Frictionless Conversion Payment","Conversion"],["Digital Engagement Maturity","Experience"],["Search Indexing Maturity","Findability"],["AI On-site Search","AI maturity"],["AI Features Benchmark","AI maturity"],
  ["AI Personalization","AI maturity"],["Conversational AI","AI maturity"],["Agentic Automation","AI maturity"],["AI Agent Readiness","AI maturity"],["MCP Transaction Surface","AI maturity"],["Brand Guideline Adherence","Brand & trust"],["Brand Consistency","Brand & trust"],["Online Reputation","Brand & trust"],["Competitor Content Marketing","Competitive"],["Structured Data Schema","Findability"],
  ["Structured Data Rich Results","Findability"],["E-E-A-T Signals","Brand & trust"],["Social Media Integration","Engagement"],["Email Lead Capture Maturity","Conversion"],["Intl Localization","Experience"],["Domain Authority Backlinks","Findability"],["Competitor Benchmark","Competitive"],["Property Subdomain Inv","Technical foundation"],["Design System Maturity","Experience"],["Landing Page Structural","Conversion"],
] as const;
const baselineGroups=[...new Set(baselineModules.map(module=>module[1]))];
const workbookRows:Record<string,string[][]>={
  "CWV":[["Performance score","Mobile 59","Desktop 75","Mobile materially behind desktop"],["LCP","Mobile 4.6s","Desktop 1.0s","Major mobile fail; target <=2.5s"],["CLS","Mobile 0.016","Desktop 0.008","Pass on both; target <=0.1"],["INP","Mobile 314ms","Desktop 102ms","Mobile interaction needs improvement"],["TTFB","Mobile 1.0s","Desktop 0.8s","Server response above ideal budget"]],
  "Accessibility":[["Lighthouse accessibility score","Mobile 94","Desktop 93","High score, but not compliance-ready"],["WAVE errors","Mobile n/a","Desktop 16","Critical desktop issues found"],["WAVE alerts","Mobile n/a","Desktop 78","High volume of structural signals"],["Manual WCAG validation","Not completed","Not completed","Required before compliance claim"]],
  "Best Practices":[["Lighthouse Best Practices score","Homepage: Mobile 69 / Desktop 46","MegaMax PDP: Mobile 69 / Desktop 69","Homepage desktop is lower"],["Deprecated APIs","Homepage: 1 warning","PDP: 2 warnings","Platform technical debt across templates"],["Browser console errors","Logged on mobile and desktop","Logged on mobile and desktop","Unresolved runtime issues"]],
  "SEO":[["Lighthouse SEO score","Homepage 92","PDP 92","Good score, but technical debt remains"],["Semrush Site Audit","6 errors / 11 warnings / 11 notices","PDP impacted by domain-level issues","Issue count requires remediation"],["Sitemap and robots","4 incorrect sitemap pages","Same indexability risk extends to PDPs","Crawl and index efficiency risk"],["Page titles and H1s","Repeated template issues","Repeated template issues","Template governance needed"]],
  "GEO":[["AI Visibility","Global 30/100","MegaMax appears in cited page set","US split not explicit"],["Monthly audience","1.15M global","Market context 110.03M","Need market-level tracking"],["Mentions","108 brand mentions","Product-intent prompts include MegaMax","Citation quality requires validation"]],
  "Security":[["Qualys SSL Labs grade","A+","Domain-level control","Strong TLS baseline"],["TLS protocol posture","TLS 1.3/1.2 enabled","Legacy protocols disabled","Continue certificate governance"],["Security headers","Core controls present","Permissions-Policy warning","Policy completeness gap remains"]],
  "Infrastructure":[["Uptime availability","100% in last 30 days","PDP inherits domain posture","Continue route-level monitoring"],["Response time","Average 556 ms","PDP not separately baselined","Need route-level latency baseline"],["Pingdom performance grade","D 68","PDP not measured","Delivery efficiency remains weak"]],
  "Data Layer & Cookies":[["DataLayer presence","Active events confirmed","Shared implementation","Coverage and quality not validated"],["Core event firing","GTM and consent events observed","Template split unavailable","Need page-template event baseline"],["Consent-event integration","OneTrust lifecycle events firing","Shared implementation","Validate consent gates tags correctly"]],
};
const genericWorkbookRows=(name:string)=>[
  ["Assessment framing",`${name} evidence collected across the current digital estate.`,"Establishes the current-state maturity baseline.","Confirm internal ownership and success criteria."],
  ["Observed capability",`Outside-in evidence and tool outputs are available for ${name.toLowerCase()}.`,"Shows the impact on customer experience and business performance.","Validate with internal analytics and operational data."],
  ["Coverage and governance","Representative homepage, product, and supporting journeys reviewed.","Creates a repeatable benchmark for future assessments.","Add owners, targets, monitoring cadence, and remediation plan."],
  ["Next validation","Additional source access or manual review is required.","Improves confidence before assessment scoring.","Resolve open validation items before baseline lock."],
];
const moduleScore=(index:number)=>Math.max(42,Math.min(96,68+((index*7)%27)-6));
const moduleStatus=(index:number)=>index%9===0?"action_needed":index%4===0?"review":"ready";

export function Baseline() {
  const {state,lockBaseline}=useStore(); const [selected,setSelected]=useState("CWV"); const [query,setQuery]=useState("");
  const selectedIndex=baselineModules.findIndex(module=>module[0]===selected); const selectedModule=baselineModules[selectedIndex]; const rows=workbookRows[selected]??genericWorkbookRows(selected); const status=moduleStatus(selectedIndex); const score=moduleScore(selectedIndex);
  const visibleGroups=baselineGroups.map(group=>({group,modules:baselineModules.filter(module=>module[1]===group&&module[0].toLowerCase().includes(query.toLowerCase()))})).filter(item=>item.modules.length);
  return <><StageNav/><PageHead eyebrow={`BASELINE.XLSX · 40 WORKSHEETS · UPDATED ${exactTime()}`} title={`${state.workspaceName} baseline workbook`} description="A digital health baseline structured exactly around the assessment workbook's 40 capability sheets." actions={<><Status value={state.baselineLocked?"locked":"validating"}/><Dialog><DialogTrigger asChild><Button disabled={state.baselineLocked}><LockKeyhole size={16}/>{state.baselineLocked?"Workbook locked":"Lock baseline workbook"}</Button></DialogTrigger><DialogContent><DialogTitle>Lock all 40 baseline sheets?</DialogTitle><p>This confirms the entire workbook as the source for snapshots and assessment generation.</p><div className="dialog-actions"><Button onClick={lockBaseline}>Confirm and lock workbook</Button></div></DialogContent></Dialog></>}/>
    <div className="stats-grid"><Stat icon={FileBarChart} label="Workbook sheets" value="40" change={`${baselineGroups.length} capability groups`}/><Stat icon={CheckCircle2} label="Sheets ready" value="31" change="77.5% workbook readiness" color="green"/><Stat icon={CircleAlert} label="Need review" value="9" change="4 require action" color="orange"/><Stat icon={ShieldCheck} label="Evidence confidence" value="High" change="Outside-in baseline + validation" color="blue"/></div>
    <div className="workbook-shell"><aside className="workbook-nav"><div className="workbook-search"><Search size={15}/><Input placeholder="Search 40 sheets..." value={query} onChange={event=>setQuery(event.target.value)}/></div><div className="workbook-count"><span>BASELINE WORKSHEETS</span><Badge>40</Badge></div>{visibleGroups.map(item=><section key={item.group}><strong>{item.group}</strong>{item.modules.map(module=>{const index=baselineModules.findIndex(candidate=>candidate[0]===module[0]);return <button key={module[0]} className={selected===module[0]?"active":""} onClick={()=>setSelected(module[0])}><span>{index+1}</span><em>{module[0]}</em><i className={moduleStatus(index)}/></button>})}</section>)}</aside>
      <main className="workbook-sheet"><Card className="sheet-summary"><CardHeader><div><span className="eyebrow">SHEET {selectedIndex+1} OF 40 · {selectedModule[1].toUpperCase()}</span><h2>{selected}</h2><p>{selected==="CWV"?"NorthShoreCare.com CWV gaps across homepage and MegaMax PDP.":`${selected} baseline with observed evidence, business impact, and validation gaps.`}</p></div><div className="sheet-score"><strong>{score}</strong><span>Sheet score</span><Status value={status}/></div></CardHeader><CardContent><div className="sheet-meta"><span><b>{rows.length}</b><small>Baseline rows shown</small></span><span><b>{score>=80?"High":score>=65?"Medium":"Low"}</b><small>Confidence</small></span><span><b>{status==="ready"?"0":status==="review"?"2":"4"}</b><small>Open validations</small></span><span><b>Jun 11 · 10:42 AM</b><small>Last updated</small></span></div></CardContent></Card>
        <Card className="spreadsheet-card"><CardHeader><div><h3>{selected} baseline</h3><p>Workbook-style evidence grid from baseline.xlsx.</p></div><div className="head-actions"><Badge>Sheet {selectedIndex+1}</Badge><Button size="sm" variant="secondary">Add evidence</Button></div></CardHeader><CardContent><div className="spreadsheet-grid"><table><thead><tr><th className="row-number">#</th><th>{["CWV","Accessibility"].includes(selected)?"Metric":"Metric / Area"}</th><th>{["CWV","Accessibility"].includes(selected)?"Mobile / Homepage":"Observed Evidence"}</th><th>{["CWV","Accessibility"].includes(selected)?"Desktop / PDP":"Business Impact"}</th><th>Gap / Validation Needed</th><th>Status</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${selected}-${index}`}><td className="row-number">{index+5}</td><td><strong>{row[0]}</strong></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><Status value={index===rows.length-1&&status!=="ready"?"review":"ready"}/></td></tr>)}</tbody></table></div></CardContent></Card>
        <div className="sheet-bottom"><Card><CardHeader><h3>Sheet review checklist</h3><Badge>{status==="ready"?"Complete":"Open"}</Badge></CardHeader><CardContent className="baseline-gates">{[["Evidence collected",true],["Business impact documented",true],["Gap and validation need documented",status==="ready"],["Internal source validation",status==="ready"],["Ready for assessment scoring",status==="ready"]].map(([label,done])=><div key={String(label)} className={done?"done":""}>{done?<CheckCircle2/>:<CircleAlert/>}<span>{label}</span></div>)}</CardContent></Card><Card><CardHeader><h3>Analyst note</h3><span className="save-state"><CheckCircle2 size={14}/>Saved</span></CardHeader><CardContent><Textarea defaultValue={`Validate the ${selected} findings with the capability owner and attach any available internal evidence before locking baseline.xlsx.`}/></CardContent></Card></div>
      </main></div></>;
}

function Snapshots() {
  const snaps=[["Internal health snapshot","Health","completed","Today, 10:32 AM","v1"],["Competitive position snapshot","Competitive","completed","Today, 10:38 AM","v1"],["Trend snapshot","Trend","waiting_for_input","Not enough history","—"]];
  return <><StageNav/><PageHead eyebrow="SNAPSHOT MANAGER" title="Point-in-time intelligence" description="Generate, compare, and preserve views of the locked baseline." actions={<Button><Plus size={16}/>Generate snapshot</Button>}/><div className="snapshot-grid">{snaps.map((s,i)=><Card key={s[0]}><CardHeader><div className={`snapshot-icon s${i}`}><FileBarChart/></div><Status value={s[2]}/></CardHeader><CardContent><h3>{s[0]}</h3><p>{s[1]} view generated from Baseline v1.</p><div className="summary-list"><span><small>Captured</small><b>{s[3]}</b></span><span><small>Version</small><b>{s[4]}</b></span></div><Button variant="secondary">{i===2?"View requirements":"Open snapshot"}<ArrowRight size={15}/></Button></CardContent></Card>)}</div><Card><CardHeader><h3>Compare snapshots</h3><Button variant="secondary">Choose snapshots</Button></CardHeader><CardContent><div className="comparison-chart">{[45,68,54,81,72,88,76,92,84,97].map((h,i)=><span key={i} style={{height:`${h}%`}}/> )}</div><div className="chart-labels"><span>Experience</span><span>Discovery</span><span>Content</span><span>Conversion</span><span>Trust</span></div></CardContent></Card></>;
}

function AssessmentEditor() {
  const {state,updatePage,addPage,movePage}=useStore(); const [selected,setSelected]=useState(state.pages[0].id); const page=state.pages.find(p=>p.id===selected)!;
  return <><StageNav/><PageHead eyebrow="ASSESSMENT EDITOR" title="Structured report pages" description="Edit narratives, scores, evidence, ordering, and page-level status." actions={<><Link to="/app/run/preview"><Button variant="secondary">Preview</Button></Link><Button onClick={addPage}><Plus size={16}/>Add page</Button></>}/><div className="editor"><aside className="page-list"><div><strong>REPORT PAGES</strong><Badge>{state.pages.length}</Badge></div>{state.pages.map((p,i)=><button key={p.id} className={selected===p.id?"active":""} onClick={()=>setSelected(p.id)}><span>{i+1}</span><div><strong>{p.title}</strong><small>{p.group}</small></div><Status value={p.status}/></button>)}</aside><Card className="editor-main"><CardHeader><div><span className="eyebrow">{page.templateId}</span><h2>{page.title}</h2><p>{page.group} · Client visible</p></div><div className="head-actions"><Button variant="ghost" size="icon" onClick={()=>movePage(page.id,-1)}><ArrowUp size={16}/></Button><Button variant="ghost" size="icon" onClick={()=>movePage(page.id,1)}><ArrowDown size={16}/></Button><Status value={page.status}/></div></CardHeader><CardContent><Tabs defaultValue="content"><TabsList><TabsTrigger value="content">Content</TabsTrigger><TabsTrigger value="metrics">Metrics</TabsTrigger><TabsTrigger value="evidence">Evidence</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList><TabsContent value="content" className="editor-fields"><label>Page title<Input value={page.title} onChange={e=>updatePage(page.id,{title:e.target.value})}/></label><label>Executive narrative<Textarea value={page.summary} onChange={e=>updatePage(page.id,{summary:e.target.value})}/></label><div className="form-grid"><label>Overall score<Input type="number" value={page.score} onChange={e=>updatePage(page.id,{score:Number(e.target.value)})}/></label><label>Review status<select className="input" value={page.status} onChange={e=>updatePage(page.id,{status:e.target.value as ReportPage["status"]})}><option value="draft">Draft</option><option value="needs_review">Needs review</option><option value="approved">Approved</option></select></label></div><div className="save-state"><CheckCircle2 size={16}/>Changes saved locally</div></TabsContent><TabsContent value="metrics"><MetricGrid page={page}/></TabsContent><TabsContent value="evidence"><div className="empty-small"><FileText/><strong>126 evidence points connected</strong><p>Evidence references are grouped by metric and source.</p></div></TabsContent><TabsContent value="history"><div className="activity-list"><div><span className="activity-dot active"/><div><strong>Narrative updated by Alex</strong><p>Clarified priority opportunity language.</p><small>10 minutes ago</small></div></div><div><span className="activity-dot"/><div><strong>Page generated</strong><p>Created from Digital Health Assessment v1.</p><small>Today at 9:45 AM</small></div></div></div></TabsContent></Tabs></CardContent></Card></div></>;
}

function ScoreRing({score}:{score:number}) {return <div className="score-ring" style={{"--score":`${score*3.6}deg`} as React.CSSProperties}><div><strong>{score}</strong><small>of 100</small></div></div>}
function MetricGrid({page}:{page:ReportPage}) {return <div className="metric-grid">{page.metrics.map(m=><div key={m.label}><small>{m.label}</small><strong>{m.value}</strong><Badge className={m.positive?"positive":"negative"}>{m.delta}</Badge></div>)}</div>}
function ReportCanvas({page,device="desktop"}:{page:ReportPage;device?:string}) {
  return <article className={`report-canvas ${device}`}><header><div><span>SIGNALOPS / LYSOL</span><h1>{page.title}</h1><p>June 2026 digital assessment · Executive report</p></div><ScoreRing score={page.score}/></header><section className="report-intro"><span className="eyebrow">EXECUTIVE SIGNAL</span><h2>{page.summary}</h2></section><MetricGrid page={page}/><section className="report-grid"><div className="report-chart"><span className="eyebrow">PERFORMANCE PROFILE</span><div>{[72,88,64,91,78,84].map((h,i)=><i key={i} style={{height:`${h}%`}}><b>{h}</b></i>)}</div><footer><span>Experience</span><span>Trust</span><span>Discovery</span><span>Content</span><span>Retail</span><span>Signal</span></footer></div><div className="recommendations"><span className="eyebrow">PRIORITY ACTIONS</span>{["Connect the brand-to-retail journey","Close mobile performance gaps","Scale accessible content patterns"].map((x,i)=><div key={x}><b>0{i+1}</b><span><strong>{x}</strong><small>{["High impact · 30 days","High confidence · 60 days","Strategic · 90 days"][i]}</small></span></div>)}</div></section><footer className="report-footer"><span>SignalOps intelligence</span><span>Confidential · Lysol · June 2026</span></footer></article>;
}

function Preview() {
  const {state,createShareLink}=useStore(); const [selected,setSelected]=useState(state.pages[0].id); const [device,setDevice]=useState("desktop"); const [copied,setCopied]=useState(false); const page=state.pages.find(p=>p.id===selected)!;
  const shareUrl=state.shareToken?`${window.location.origin}/shared/reports/${state.shareToken}`:"";
  const ensureShare=()=>{const token=createShareLink();return `${window.location.origin}/shared/reports/${token}`};
  const copyShare=async()=>{const url=shareUrl||ensureShare();await navigator.clipboard?.writeText(url);setCopied(true);window.setTimeout(()=>setCopied(false),1800)};
  return <><StageNav/><PageHead eyebrow={`ASSESSMENT PREVIEW · UPDATED ${exactTime()}`} title="Responsive report viewer" description="Review every report page exactly as clients will experience it, then create one reusable client-safe preview link." actions={<><Button variant="secondary" onClick={copyShare}>{copied?<Check size={16}/>:<Share2 size={16}/>} {copied?"Link copied":"Share preview"}</Button><Link to="/app/run/review"><Button>Submit for review<ArrowRight size={16}/></Button></Link></>}/>
    <Card className="share-panel"><CardContent><div className="share-heading"><span className="share-icon"><Link2/></span><div><span className="eyebrow">SHAREABLE PREVIEW LINK</span><h3>{shareUrl?"Client preview link is active":"Create one client preview link"}</h3><p>{shareUrl?"Anyone with this local demo link can open the client-safe report preview.":"Generate a persistent link for this assessment directly from Preview."}</p></div></div>{shareUrl?<div className="share-link-area"><div className="share-url"><Input readOnly value={shareUrl}/><Button variant="secondary" onClick={copyShare}><Copy size={16}/>{copied?"Copied":"Copy"}</Button><a href={shareUrl} target="_blank" rel="noreferrer"><Button><ExternalLink size={16}/>Open</Button></a></div><div className="share-meta"><span><Clock3 size={14}/><strong>Created</strong> {state.shareCreatedAt?exactTime(new Date(state.shareCreatedAt)):"Just now"}</span><span><CalendarDays size={14}/><strong>Expires</strong> {state.shareExpiresAt?exactTime(new Date(state.shareExpiresAt)):"30 days after creation"}</span><Status value={state.assessmentStatus==="published"?"published":"preview"}/></div></div>:<Button onClick={ensureShare}><Share2 size={16}/>Generate shareable preview link</Button>}</CardContent></Card>
    <div className="preview-toolbar"><div className="preview-pages">{state.pages.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} className={p.id===selected?"active":""}>{p.title}<Status value={p.status}/></button>)}</div><div className="device-switch">{["desktop","tablet","mobile"].map(d=><Button key={d} size="sm" variant={device===d?"default":"ghost"} onClick={()=>setDevice(d)}>{titleCase(d)}</Button>)}</div></div><div className="preview-stage"><ReportCanvas page={page} device={device}/></div></>;
}

function Review() {
  const {state,setAssessmentStatus,publish}=useStore(); const navigate=useNavigate();
  const openCount=state.pages.filter(p=>p.status!=="approved"&&p.status!=="published").length;
  return <><StageNav/><PageHead eyebrow="REVIEW & APPROVAL" title="Publication readiness" description="Resolve remaining issues, approve the assessment, and create a client-safe report." actions={<Status value={state.assessmentStatus}/>}/><div className="review-layout"><Card><CardHeader><h3>Review checklist</h3><Badge>{openCount} items open</Badge></CardHeader><CardContent className="checklist">{[["Baseline locked",state.baselineLocked],["All pages reviewed",openCount===0],["Evidence requirements met",true],["Client visibility confirmed",true],["Publication approval",state.assessmentStatus==="approved"||state.assessmentStatus==="published"]].map(([x,done])=><div key={String(x)} className={done?"done":""}>{done?<CheckCircle2/>:<CircleAlert/>}<span><strong>{x}</strong><small>{done?"Complete":"Action required"}</small></span></div>)}</CardContent></Card><Card className="span-2"><CardHeader><div><h3>Report page readiness</h3><p>Approve pages independently or publish the complete set.</p></div></CardHeader><CardContent><table><thead><tr><th>Report page</th><th>Score</th><th>Visibility</th><th>Status</th></tr></thead><tbody>{state.pages.map(p=><tr key={p.id}><td><strong>{p.title}</strong><small className="table-sub">{p.group}</small></td><td><b className="score-cell">{p.score}</b></td><td>{titleCase(p.visibility)}</td><td><Status value={p.status}/></td></tr>)}</tbody></table><div className="approval-bar"><div><strong>Assessment decision</strong><p>Role: {titleCase(state.role)} · {can(state.role,"approve")?"Approval permitted":"Approval requires reviewer role"}</p></div><Button variant="secondary" disabled={!can(state.role,"approve")} onClick={()=>setAssessmentStatus("changes_requested")}><XCircle size={16}/>Request changes</Button><Button disabled={!can(state.role,"approve")} onClick={()=>setAssessmentStatus("approved")}><Check size={16}/>Approve</Button><Button disabled={!can(state.role,"publish")||state.assessmentStatus!=="approved"} onClick={()=>{const t=publish();navigate(`/shared/reports/${t}`)}}><Share2 size={16}/>Publish</Button></div></CardContent></Card></div></>;
}

function Jobs() {const {state,retryJob}=useStore();return <><PageHead eyebrow="OPERATIONS" title="Generation jobs" description="Monitor long-running report work across every client workspace." actions={<Button variant="secondary"><RefreshCcw size={16}/>Refresh state</Button>}/><div className="stats-grid three"><Stat icon={Activity} label="Running" value="3" change="Across 2 workspaces"/><Stat icon={CircleAlert} label="Needs attention" value="2" change="One retry available" color="orange"/><Stat icon={CheckCircle2} label="Completed today" value="14" change="98% success rate" color="green"/></div><Card><CardHeader><div className="search"><Search size={17}/><Input placeholder="Search jobs..."/></div><div className="filter-row"><Badge>All states</Badge><Badge>All workspaces</Badge><Badge>Today</Badge></div></CardHeader><CardContent><JobTable jobs={state.jobs} onRetry={retryJob}/></CardContent></Card></>}
function Notifications(){const {state,markRead}=useStore();return <><PageHead eyebrow="INBOX" title="Notifications" description="Updates, required actions, and report activity across your organization." actions={<Button variant="secondary" onClick={markRead}>Mark all read</Button>}/><Card><CardContent className="notification-list">{state.notifications.map(n=><Link to="/app/run" key={n.id} className={n.read?"":"unread"}><span className="notification-icon"><Bell/></span><div><strong>{n.title}</strong><p>{n.message}</p><small>Today · Lysol workspace</small></div><ChevronRight/></Link>)}</CardContent></Card></>}
function SettingsPage(){const {state,setRole,reset}=useStore();return <><PageHead eyebrow="PRODUCT SETTINGS" title="Demo and preferences" description="Control the frontend-only workspace behavior and inspect role capabilities."/><div className="settings-grid"><Card><CardHeader><h3>Demo identity</h3></CardHeader><CardContent className="settings-form"><label>Active role<select className="input" value={state.role} onChange={e=>setRole(e.target.value as Role)}>{roles.map(r=><option value={r} key={r}>{titleCase(r)}</option>)}</select></label><div className="capability-grid">{["edit","review","approve","publish","manage","retry"].map(c=><Badge key={c} className={can(state.role,c)?"success":"muted"}>{can(state.role,c)?<Check size={13}/>:<XCircle size={13}/>} {titleCase(c)}</Badge>)}</div></CardContent></Card><Card><CardHeader><h3>Local demo data</h3></CardHeader><CardContent><p>This frontend stores all jobs, reports, roles, and share links in this browser. No information is sent to a backend.</p><Button variant="destructive" onClick={reset}><RefreshCcw size={16}/>Reset demo data</Button></CardContent></Card></div></>}

function SharedReport(){const {token}=useParams();const {state}=useStore();const [selected,setSelected]=useState(state.pages[0].id);const page=state.pages.find(p=>p.id===selected)!;const valid=state.shareToken===token&&(!state.shareExpiresAt||new Date(state.shareExpiresAt)>new Date());if(!valid)return <div className="shared-error"><LockKeyhole/><h1>This report link is unavailable</h1><p>The local demo token is invalid or has expired.</p><Link to="/login"><Button>Return to sign in</Button></Link></div>;return <div className="shared-view"><header><div className="brand"><span className="brand-mark"><BarChart3/></span><span><b>SignalOps</b><small>Client report</small></span></div><div><Badge className="success">Published</Badge><Button variant="secondary"><ExternalLink size={16}/>Export</Button></div></header><nav>{state.pages.filter(p=>p.visibility==="client").map(p=><button className={p.id===selected?"active":""} onClick={()=>setSelected(p.id)} key={p.id}>{p.title}</button>)}</nav><div className="shared-stage"><ReportCanvas page={page}/></div></div>}

function ProtectedRoutes(){const {state}=useStore();if(!state.signedIn)return <Navigate to="/login"/>;return <AppShell><Routes><Route index element={<Dashboard/>}/><Route path="workspaces" element={<Workspaces/>}/><Route path="workspaces/new" element={<CreateWorkspace/>}/><Route path="workspaces/:id" element={<WorkspaceOverview/>}/><Route path="workspaces/:id/new-run" element={<NewRun/>}/><Route path="admin" element={<OrganizationAdmin/>}/><Route path="run" element={<RunCommand/>}/><Route path="run/tools" element={<Tools/>}/><Route path="run/baseline" element={<BaselinePage/>}/><Route path="run/snapshots" element={<Snapshots/>}/><Route path="run/assessment" element={<AssessmentEditor/>}/><Route path="run/preview" element={<Preview/>}/><Route path="run/review" element={<Review/>}/><Route path="jobs" element={<Jobs/>}/><Route path="notifications" element={<Notifications/>}/><Route path="settings" element={<SettingsPage/>}/><Route path="*" element={<Navigate to="/app"/>}/></Routes></AppShell>}

export default function App(){return <StoreProvider><Routes><Route path="/login" element={<Login/>}/><Route path="/shared/reports/:token" element={<SharedReport/>}/><Route path="/app/*" element={<ProtectedRoutes/>}/><Route path="*" element={<Navigate to="/app"/>}/></Routes></StoreProvider>}
